repos:
  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3.8
        exclude: ingestion/src/metadata/generated
  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: ingestion/src/metadata/generated
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.2.4
    hooks:
      - id: pycln
        exclude: ingestion/src/metadata/generated
